using System;
using System.Buffers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

namespace PullSub.Core
{
    /// <summary>
    /// Standard typed codec for Flat JSON format.
    /// The payload format is <c>{ "timestamp": "...", ...properties of T... }</c>.
    /// The <c>timestamp</c> key is reserved and must not be used as a property name in T.
    /// T must be a type (class or struct) that serializes as a JSON object.
    /// </summary>
    public sealed class FlatJsonPayloadCodec<T> : TextPayloadCodec<T>
    {
        private static readonly JsonSerializerOptions DefaultOptions = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };

        public static readonly FlatJsonPayloadCodec<T> Default = new FlatJsonPayloadCodec<T>();

        private readonly JsonSerializerOptions _options;
        private readonly JsonTypeInfo<T> _typeInfo;

        public FlatJsonPayloadCodec(JsonSerializerOptions options = null)
        {
            _options = options ?? DefaultOptions;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FlatJsonPayloadCodec{T}"/> class using
        /// <see cref="JsonTypeInfo{T}"/> generated by a Source Generator.
        /// This avoids reflection entirely and prevents code stripping in IL2CPP environments.
        /// <para>
        /// Note that <see cref="JsonSerializerOptions"/> settings like <c>PropertyNameCaseInsensitive</c>
        /// are not applied. Use the constructor that accepts <see cref="JsonSerializerOptions"/> if those are required.
        /// </para>
        /// </summary>
        public FlatJsonPayloadCodec(JsonTypeInfo<T> typeInfo)
        {
            _typeInfo = typeInfo ?? throw new ArgumentNullException(nameof(typeInfo));
            _options = null;
        }

        public override bool Equals(object obj)
        {
            return obj is FlatJsonPayloadCodec<T> other
                && ReferenceEquals(_typeInfo, other._typeInfo)
                && ReferenceEquals(_options, other._options);
        }

        public override int GetHashCode()
        {
            return _typeInfo?.GetHashCode() ?? _options.GetHashCode();
        }

        public override void Encode(DateTime timestampUtc, T value, IBufferWriter<byte> bufferWriter)
        {
            if (bufferWriter == null)
                throw new ArgumentNullException(nameof(bufferWriter));

            var normalized = NormalizeTimestampOrNow(timestampUtc);
            using var writer = new Utf8JsonWriter(bufferWriter);
            writer.WriteStartObject();
            writer.WriteString("timestamp", normalized);

            var tBytes = _typeInfo != null
                ? JsonSerializer.SerializeToUtf8Bytes(value, _typeInfo)
                : JsonSerializer.SerializeToUtf8Bytes(value, _options);
            using var tDoc = JsonDocument.Parse(tBytes);
            if (tDoc.RootElement.ValueKind != JsonValueKind.Object)
                throw new InvalidOperationException("FlatJsonPayloadCodec<T> requires T to serialize as a JSON object.");

            foreach (var prop in tDoc.RootElement.EnumerateObject())
            {
                if (prop.Name.Equals("timestamp", StringComparison.Ordinal))
                {
                    throw new InvalidOperationException(
                        "Property name 'timestamp' is reserved by FlatJsonPayloadCodec<T>. Use a different property name.");
                }

                prop.WriteTo(writer);
            }

            writer.WriteEndObject();
        }

        public override bool TryDecode(ReadOnlySpan<byte> payload, out T value, out DateTime timestampUtc, out string error)
        {
            value = default;
            timestampUtc = default;
            error = null;

            if (payload.IsEmpty)
            {
                error = "payload is empty.";
                return false;
            }

            try
            {
                var reader = new Utf8JsonReader(payload);
                using var doc = JsonDocument.ParseValue(ref reader);
                var root = doc.RootElement;

                if (root.ValueKind != JsonValueKind.Object)
                {
                    error = "Flat JSON payload root must be a JSON object.";
                    return false;
                }

                if (root.TryGetProperty("timestamp", out var tsProp) && tsProp.TryGetDateTime(out var ts))
                    timestampUtc = ts.Kind == DateTimeKind.Utc ? ts : ts.ToUniversalTime();
                else
                    timestampUtc = DateTime.UtcNow;

                // Reconstruct T from all properties except "timestamp".
                var buffer = new ArrayBufferWriter<byte>(payload.Length);
                using (var writer = new Utf8JsonWriter(buffer))
                {
                    writer.WriteStartObject();
                    foreach (var prop in root.EnumerateObject())
                    {
                        if (!prop.Name.Equals("timestamp", StringComparison.Ordinal))
                            prop.WriteTo(writer);
                    }
                    writer.WriteEndObject();
                }

                value = _typeInfo != null
                    ? JsonSerializer.Deserialize(buffer.WrittenSpan, _typeInfo)
                    : JsonSerializer.Deserialize<T>(buffer.WrittenSpan, _options);
                return true;
            }
            catch (Exception ex)
            {
                error = ex.Message;
                return false;
            }
        }

        protected override string FormatPayload(DateTime timestampUtc, T value)
        {
            var buffer = new ArrayBufferWriter<byte>(256);
            Encode(timestampUtc, value, buffer);
            return Encoding.UTF8.GetString(buffer.WrittenSpan);
        }

        protected override bool TryParsePayload(string text, out T value, out DateTime timestampUtc, out string error)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                value = default;
                timestampUtc = default;
                error = "payload text is empty.";
                return false;
            }

            return TryDecode(Encoding.UTF8.GetBytes(text), out value, out timestampUtc, out error);
        }
    }
}
