using System;
using System.Buffers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

namespace PullSub.Core
{
    /// <summary>
    /// Default typed codec for JSON envelope format.
    /// The payload format is <c>{ "timestamp": "...", "data": { ...properties of T... } }</c>.
    /// </summary>
    public sealed class JsonPayloadCodec<T> : TextPayloadCodec<T>
    {
        private static readonly JsonSerializerOptions DefaultOptions = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };

        public static readonly JsonPayloadCodec<T> Default = new JsonPayloadCodec<T>();

        private readonly JsonSerializerOptions _options;
        private readonly JsonTypeInfo<T> _typeInfo;

        public JsonPayloadCodec(JsonSerializerOptions options = null)
        {
            _options = options ?? DefaultOptions;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JsonPayloadCodec{T}"/> class using
        /// <see cref="JsonTypeInfo{T}"/> generated by a Source Generator.
        /// This avoids reflection entirely and prevents code stripping in IL2CPP environments.
        /// <para>
        /// Note that <see cref="JsonSerializerOptions"/> settings like <c>PropertyNameCaseInsensitive</c>
        /// are not applied. Use the constructor that accepts <see cref="JsonSerializerOptions"/> if those are required.
        /// </para>
        /// </summary>
        public JsonPayloadCodec(JsonTypeInfo<T> typeInfo)
        {
            _typeInfo = typeInfo ?? throw new ArgumentNullException(nameof(typeInfo));
            _options = null;
        }

        public override bool Equals(object obj)
        {
            return obj is JsonPayloadCodec<T> other
                && ReferenceEquals(_typeInfo, other._typeInfo)
                && ReferenceEquals(_options, other._options);
        }

        public override int GetHashCode()
        {
            return _typeInfo?.GetHashCode() ?? _options.GetHashCode();
        }

        public override void Encode(DateTime timestampUtc, T value, IBufferWriter<byte> bufferWriter)
        {
            if (bufferWriter == null)
                throw new ArgumentNullException(nameof(bufferWriter));

            var normalized = NormalizeTimestampOrNow(timestampUtc);
            using var writer = new Utf8JsonWriter(bufferWriter);
            writer.WriteStartObject();
            writer.WriteString("timestamp", normalized);
            writer.WritePropertyName("data");
            if (_typeInfo != null)
                JsonSerializer.Serialize(writer, value, _typeInfo);
            else
                JsonSerializer.Serialize(writer, value, _options);
            writer.WriteEndObject();
        }

        public override bool TryDecode(ReadOnlySpan<byte> payload, out T value, out DateTime timestampUtc, out string error)
        {
            value = default;
            timestampUtc = default;
            error = null;

            if (payload.IsEmpty)
            {
                error = "payload is empty.";
                return false;
            }

            try
            {
                var reader = new Utf8JsonReader(payload);
                if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)
                {
                    error = "JSON root must be an object.";
                    return false;
                }

                long dataStart = -1;
                long dataEnd = -1;
                bool gotTimestamp = false;

                while (reader.Read() && reader.TokenType != JsonTokenType.EndObject)
                {
                    if (reader.TokenType != JsonTokenType.PropertyName)
                    {
                        error = "Unexpected token in root object.";
                        return false;
                    }

                    if (reader.ValueTextEquals("timestamp"))
                    {
                        reader.Read();
                        if (reader.TryGetDateTime(out var ts))
                            timestampUtc = ts.Kind == DateTimeKind.Utc ? ts : ts.ToUniversalTime();
                        else
                            timestampUtc = DateTime.UtcNow;
                        gotTimestamp = true;
                    }
                    else if (reader.ValueTextEquals("data"))
                    {
                        reader.Read();
                        dataStart = reader.TokenStartIndex;
                        reader.Skip();
                        dataEnd = reader.BytesConsumed;
                    }
                    else
                    {
                        reader.Read();
                        reader.Skip();
                    }
                }

                if (!gotTimestamp)
                    timestampUtc = DateTime.UtcNow;

                if (dataStart < 0)
                {
                    error = "Missing 'data' field in JSON envelope.";
                    return false;
                }

                var dataSlice = payload.Slice((int)dataStart, (int)(dataEnd - dataStart));
                value = _typeInfo != null
                    ? JsonSerializer.Deserialize(dataSlice, _typeInfo)
                    : JsonSerializer.Deserialize<T>(dataSlice, _options);
                return true;
            }
            catch (Exception ex)
            {
                error = ex.Message;
                return false;
            }
        }

        protected override string FormatPayload(DateTime timestampUtc, T value)
        {
            var buffer = new ArrayBufferWriter<byte>(256);
            Encode(timestampUtc, value, buffer);
            return Encoding.UTF8.GetString(buffer.WrittenSpan);
        }

        protected override bool TryParsePayload(string text, out T value, out DateTime timestampUtc, out string error)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                value = default;
                timestampUtc = default;
                error = "payload text is empty.";
                return false;
            }

            return TryDecode(Encoding.UTF8.GetBytes(text), out value, out timestampUtc, out error);
        }
    }
}
