name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: '8.0.x'
      - name: Test
        run: dotnet test dotnet/tests/PullSub.Core.Tests/PullSub.Core.Tests.csproj --configuration Release